services:
  database:
    container_name: database-postgres
    image: postgres:latest
    environment:          
      - POSTGRES_DB=${DB_NAME}   
      - POSTGRES_USER=${DB_USER}        
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      app_network:
        ipv4_address: 172.28.0.2

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - ACCESS_TOKEN_LIFETIME=${ACCESS_TOKEN_LIFETIME}
      - REFRESH_TOKEN_LIFETIME=${REFRESH_TOKEN_LIFETIME}
      - ROTATE_REFRESH_TOKENS=${ROTATE_REFRESH_TOKENS}
      - BLACKLIST_AFTER_ROTATION=${BLACKLIST_AFTER_ROTATION}
      - ALGORITHM=${ALGORITHM}
    depends_on:
      - database
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24

  

